events {}
http {
    server {
        listen 443 ssl;
        server_name imanage.yeaft.com;

        ssl_certificate /etc/letsencrypt/live/yeaft.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/yeaft.com/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://imanage-flask-app:8888;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 443 ssl;
        server_name reader.yeaft.com;

        ssl_certificate /etc/letsencrypt/live/yeaft.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/yeaft.com/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://reader-app:5123;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 443 ssl;
        server_name www.yeaft.com;

        ssl_certificate /etc/letsencrypt/live/yeaft.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/yeaft.com/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://data-api-flask-app:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
